# Aldnoah_Logic/aldnoah_infos.py
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple

"""This script is where various info is stored such as names, values, etc"""

# For Weapon Editor, not a complete list since I couldn't find more weapon names

dw8xl_weapon_list = [
    "Cutlass", "Rebel's Cutlass", "Qilin Blade", "Blade of Darkness", "Demon Slayer",
    "Iron Axe", "Battle Axe", "Beast Slayer", "Royal Axe", "Roaring Axe",
    "White Whip", "Shadow Whip", "Peacock Whip", "Dragon Whip", "Royal Whip",
    "Twin Axes", "Heavy Twin Axes", "Wind Axes", "Sun & Moon", "Dragon Axes",
    "Iron Blade", "General's Glory", "Blade of Light", "Sword of Heaven", "Conqueror's Blade",
    "Oaken Staff", "Teak Staff", "Bronze-Studded Staff", "Yellow Dragon Staff", "Crimson Cloud",
    "Aerial Blades", "Swallow's Edge", "Petrel Blades", "Swallow's Fury", "Crimson Swallow",
    "Iron Hoops", "Battle Hoops", "Wind & Fire Wheels", "Astral Wheels", "Princess Wheels",
    "Chain Flail", "Snake Flail", "Adder Flail", "Demon Chain", "Godly Flail",
    "Ringed Blade", "Steel Blade", "Tiger's Strike", "Tiger's Fury", "Imperial Tiger",
    "Dragon Fang", "Dragon's Tail", "Dragon Spike", "Rising Dragon", "Heavenly Dragon",
    "Long Halberd", "Steel Halberd", "Green Dragon", "Dragon Blade", "Godly Dragon",
    "Cobra Pike", "Twin Serpents", "Serpent Blade", "Crushing Blade", "Heaven's Venom",
    "Sparrow Wing", "Swallow Wing", "Raven Wing", "Crimson Wing", "Emerald Wing",
    "Twin Swords", "Splendid Swords", "Azure Swords", "Exquisite Swords", "Heavenly Swords",
    "Iron Whip", "Steel Whip", "Jeweled Whip", "Dragon Bone", "Phoenix Spine",
    "Light Halberd", "Sturdy Halberd", "Sky Piercer", "Royal Halberd", "Soul Crusher",
    "Hex Club", "Studded Club", "Stone Crusher", "Holy Comet", "Bull Club",
    "Iron Bow", "Steel Bow", "Spiked Bow", "Heavenly Bow", "Bow of Destruction",
    "Mighty Axe", "Destructive Axe", "Fangcrusher", "White Fang", "Soulcleaver",
    "Godly Axe", "Steel Claws", "Leopard Claws", "Ghostly Claws", "Elegant Claws",
    "Bronze Wall", "Fang Wall", "Crimson Wall", "Phoenix Wall", "Talon Wall",
    "Iron Edge", "Clarity Spike", "Ice Storm", "Royal Storm", "Azure Storm",
    "Twin Rods", "Chaos Rods", "Tiger & Wolf", "Imperial Rods", "Demon Rods",
    "Iron Glaive", "Steel Glaive", "Rainmaker", "Golden Glory", "Crimson Fury",
    "Feudal Edge", "Bronze Edge", "Darkness Edge", "Azure Edge", "Tiger's Edge",
    "Claw Blade", "Swift Blade", "Dawn", "Twilight Blade", "Void",
    "Sanjiegun", "Triple Iron", "Rising Clouds", "Raging Hail", "Raging Winds",
    "Oak Tonfa", "Studded Tonfa", "Goblin Fist", "Infernal Tiger", "Conqueror's Roar",
    "Iron Sword", "Wolf's Fang", "Cloudburst", "Sword of Judgment", "Emperor's Might",
    "Iron Spear", "Battle Spear", "Silver Stallion", "Cavalry Spear", "Emerald Spear",
    "Long Bow", "Recurve Bow", "Wind Shooter", "Qilin Bow", "Demon Hunter",
    "Curved Voulge", "Master Voulge", "Sky Voulge", "Wicked Voulge", "Hellish Voulge",
    "Horse Cleaver", "Stallion Cleaver", "Tiger Splitter", "Rune Blade", "Soaring Dragon",
    "Floral Fan", "Winged Fan", "Emerald Fan", "Stormy Fan", "Leader's Fan",
    "Clay Bomb", "Shard Bomb", "Typhoon Grenade", "Heavenly Star", "Demon Bomb",
    "Distant Blade", "Distant Bronze Blade", "Thorny Blade", "Echo Blade", "Heaven's Reach",
    "Shaman Rod", "Conjurer Wand", "Turquoise Wand", "Divine Rod", "Heavenly Scepter",
    "Iron Flute", "Battle Flute", "Spirit Song", "Crimson Flute", "Pearl Flute",
    "Iron Fan", "Battle Fan", "Sparkling Draft", "Nine Heavens Fan", "Illusion Fan",
    "Iron Ge", "Battle Ge", "Moonlight", "Oblivion", "Destruction",
    "Battle Gloves", "Iron Gloves", "Badger Gauntlets", "Royal Gloves", "Shaman's Gloves",
    "Simple Harp", "Battle Harp", "Combat Harp", "Royal Harp", "Heavenly Harp",
    "Budding Staff", "Elegant Staff", "Staff of Hearts", "Staff of Dreams", "Butterfly Staff",
    "Iron Trident", "Bronze Trident", "Dual Fangs", "Dragonthroat", "Qilin Trident",
    "Harvest Sickle", "Hunting Sickle", "Dark Thresher", "Shadow Sickle", "Heavenly Sickle",
    "Flashpoint", "Blinkblade", "Imperial Flame", "Winged Glory", "Emperor's Light",
    "Rampant Blade", "Momentous Blade", "Skysplitter", "Skymaster", "Sealant Blade",
    "Iron Lance", "Battle Lance", "Wasp Sting", "Qilin Horn", "Spear of Armageddon",
    "Throwing Blades", "Combat Blades", "Rose Thorns", "Thunder Blades", "Rain Blades",
    "Razor Dance", "Razor Wind", "Gliding Cobra", "Flying Dragon", "Aerial Blade",
    "Iron Baton", "Deadly Baton", "Ebony Baton", "Quivering Blow", "Golden Might",
    "Destructive Spear", "Stonecrushing Spear", "Ironshredder", "Sky Piercer", "Spear of Conquest",
    "Battle Cannon", "War Cannon", "Boomstick", "Explosive Fury", "Earthshaker",
    "Iron Chakram", "Steel Chakram", "Shredding Chakram", "Demon Chakram", "Goblin Chakram",
    "Iron Needle", "Steel Needle", "Apex Rapier", "Scarlet Fury", "Verdant Thrust",
    "Guard Set", "Soldier Set", "Mercenary Set", "Imperial Set", "Heavenly Set",
    "Wood Crossbow", "War Crossbow", "Hornet Sting", "Eagle Claw", "Falcon Strike",
    "Bamboo Brush", "Cedar Brush", "Tiger Brush", "Emperor Brush", "Heavenly Brush",
    "Iron Boomerang", "Flying Shadow", "Triple Edge", "Trident Tusk", "Heaven's Return",
    "Wood Nunchaku", "Iron Nunchaku", "Rising Phoenix", "Crimson Wave", "Storm Wave",
    "Chopper", "Slasher", "Bloodspray", "Spinning Inferno", "Deadly Gale",
    "Iron Mace", "Battle Mace", "Rock Crusher", "Earthquake", "World Smasher",
    "Trifork", "Bronze Trifork", "Peacock's Talons", "Silver Trifork", "Azure Tip",
    "Battle Staff", "Darkness Staff", "Dapeng Rod", "Winged Grace", "Heavenly Phoenix",
    "Piercing Blade", "Kan Blade", "Soaring Blade", "Sapphire Blade", "Dispersion Blade",
    "Taoist Deck", "Cursed Deck", "Spirit Deck", "Mystic Deck", "Heavenly Deck",
    "Twin Hook", "Wicked Hook", "Fury Hook", "Conical Blade", "Talons of Conquest",
    "Studded Wheel", "Spiked Ring", "Roaring Wheel", "Flash Wheel", "Heavenly Destruction",
    "Iron Teeth", "Steel Incisors", "Armored Fangs", "Majestic Fangs", "Deadly Incisors",
    "Iron Ko", "Battle Ko", "Spring Striker", "Roaring Pike", "Stormy Pike",
    "Swooping Blade", "Sturdy Wingblade", "Steel Wingblade", "Mighty Blade", "Golden Dragon",
    "Iron Flailblade", "Elite Edge", "Gravity Blade", "Crushing Blade", "Dragonspeak",
    "Dualstone Mace", "Twin Studded Mace", "Destructive Mace", "Shocking Mace", "Dragon Smasher",
    "Dancing Shadows", "Dancing Darkness", "Dancing Enigma", "Dancing Peng", "Hidden Essence",
    "Iron Javelin", "Bronze Javelin", "Smashing Javelin", "Heavenly Javelin", "Skycrusher",
    "Sturdy Claws", "Threaded Claws", "Razor Claws", "Stinger Claws", "Purple Fury",
    "Soundshredder", "Windstinger", "Dustscatter", "Helmsplitter", "Dawning Wisdom",
    "Monsoon", "Snakedealer", "Wolfbringer", "Chariotstrike", "Reincarnation",
    "Rising Heavens", "Seven Stars", "Scorched Earth", "Raging Storm", "Snowblind",
    "Afterglow", "Spiralchain", "Waterfall", "Infinite Void", "Earthshatter",
    "Dragonjaw", "Dragonclaw", "Moonarc", "Ascending Dragon", "Wildheart",
    "Tempest", "Motionpeak", "Summitchaser", "Polar Needles", "Fellowship of Duty",
    "Earthshaker", "Boltbringer", "Nine-layered Heaven", "Towerstopper", "Boulderstrike",
    "Heavenly Summit", "Heaven's Drill", "Seabringer", "Armbender", "Mistcleaver",
    "Flowery Rage", "Reckless Light", "Brightflash", "Victorywall", "Frozen Tundra",
    "Skyjailor", "Thunderpeal", "Windwhip", "Spraycutter", "Shadowless",
    "Eternal Voyage", "Seacrusher", "Darkness", "Shadow", "Armbreaker",
    "Icebug", "Thunderclap", "Hellfire", "Flamebringer", "Windflower",
    "Spring's Light", "Flying Formation", "Violent Torrent", "Dragonbasin", "Netherworld's Fury",
    "Stinging Barb", "Sea Splitter", "Sky Splitter", "Windgust", "Timely Winds",
    "Ego Booster", "Blooming Desire", "Crimson Hornet", "Drop Thruster", "Profusion",
    "Infinity", "Ice Petals", "Firefly", "Mirage", "Distant Thunder",
    "Bottom Tide", "Lotus Blossom", "Sublimity", "Jawbreaker", "Bell Harp",
    "Lunar Melody", "Heavenly Canopy", "Floral Rain", "Tigerwolf Fang", "Whirlwind Edge",
    "Dark Mantis", "Flying Ivy", "Numbness Cloud", "Paralyzing Mist", "Grating Slasher",
    "Flash Strike", "Endless Abyss", "Aurora", "Moonlight", "Scarlet Dawn",
    "Surging Conquest", "Heavenly Ambition", "Fiery Desire", "Solemn Echo", "Kingdom Crasher",
    "Army Slayer", "Evening Flame", "Chaotic Flame", "Nightcleaver", "Gleaming Dawn",
    "Dreamsetter", "Thunderstorm", "Endless Sky", "Silent Moon", "Thunderstrike",
    "Arctic Storm", "Birds & Beasts", "Nature's Beauty", "Hawk Boomerang", "Eagle Boomerang",
    "Flamedust", "Flashbringer", "Spirit Whirl", "Morning Stroll", "Crystal Crusher",
    "Resonant Ambition", "Apex Tusk", "Sharp Claws", "Demonlight", "Ball & Sky",
    "Dragonfly Blade", "Windtail", "Yin & Yang", "Demon Sealer", "Windgale",
    "Binding Talon", "Hellish Wheel", "Dancing Ring", "Heavenly Pillar", "Ground Drill",
    "Triple Thunder", "Explosive Bolt", "Shrike Wingblade", "Lark Wingblade", "Snowblast",
    "Endless Vicissitude", "Flower Spindle", "Roaring Wave", "Sacred Dance", "Lion Dance",
    "Sudden Flash", "Light Beam", "Black Widow", "Silk Moth", "Emperor's Blade"
]

DW8XL_WEAPON_NAMES = {i: dw8xl_weapon for i, dw8xl_weapon in enumerate(dw8xl_weapon_list)}

# For Element Editor

dw8xl_elements = [
    "Thorns",
    "Awareness",
    "Survival",
    "Frenzy",
    "Barricade",
    "Aggression",
    "Flurry",
    "Velocity",
    "Chain",
    "Inferno",
    "Frost",
    "Thunder",
    "Cyclone",
    "Slash",
    "Venom",
    "Flash",
    "Spurt",
    "Recovery",
    "Uplift",
    "Enlightenment",
    "Explosive",
    "Induction",
    "Vigor",
    "Jolt",
    "Desperation",
    "Resolve",
    "Swiftness",
    "Agility",
    "Harmony",
    "Protection",
    "Fear",
    "Awe",
    "Morass",
    "Jubilation",
    "Roar",
    "Triumph",
    "Greed",
    "Fury",
    "Rigidity",
    "Whirlwind",
    "Gale",
    "Comet",
    "Thunderclap",
    "Efflorescence",
    "Conflagration",
    "Battleaxe",
    "Armor Sleeve",
    "War Shoes",
    "Rakshasa",
    "Shining Warrior"
]

DW8XL_ELEMENT_NAMES = {i: dw8xl_element for i, dw8xl_element in enumerate(dw8xl_elements)}

dw8xl_element_descriptions = [
    "Returns a portion of the damage suffered to the enemy.",
    "Able to guard against attacks from behind.",
    "The lower your Health is, the more your Attack increases.",
    "Your Attack increases greatly, but your Defense decreases.",
    "Your Defense increases greatly, but your Attack decreases.",
    "Increases the damage inflicted by your Musou Attack.",
    "Increases the damage inflicted by consecutive attacks.",
    "Increases your Attack Speed.",
    "Increases the amount of time that chains can be linked together.",
    "Adds additional fire damage to your attacks.",
    "Your attacks may freeze the enemy, rendering them immobile.",
    "Lightning will shoot out from enemies you attack.",
    "Inflict some damage on even enemies that are guarding.",
    "Inflict additional damage against the enemy or even defeat them in a single blow.",
    "Inflict poison damage on enemies.",
    "Cause enemies that have accumulated damage to explode.",
    "Defeated enemies will drop Winged Boots.",
    "Your Health Gauge will recover somewhat with each successful attack.",
    "Your Musou Gauge will recover somewhat with each successful attack.",
    "Your Rage Gauge will recover somewhat with each successful attack.",
    "A powerful shockwave may be unleashed following a successful attack.",
    "Lightning may strike the enemy following a successful attack.",
    "A shockwave may be emitted when you take damage from the enemy.",
    "Lightning may be emitted when you take damage from the enemy.",
    "Attack doubles when near death and getting up from the ground.",
    "Defense doubles when near death and getting up from the ground.",
    "Speed doubles when near death and getting up from the ground.",
    "Unleash your fighting spirit when successfully executing a somersault.",
    "Attack increases when both of your weapons have the same Affinity.",
    "Defense increases when both of your weapons have the same Affinity.",
    "Your attacks may frighten enemies.",
    "Your attacks may stun the enemy.",
    "Your attacks may decrease the enemy's Speed and Attack Speed.",
    "Recover a portion of your Health Gauge when you defeat an enemy.",
    "Recover a portion of your Musou Gauge when you defeat an enemy.",
    "Recover a portion of your Rage Gauge when you defeat an enemy.",
    "Obtain Gold when landing an attack on enemies who are guarding.",
    "Able to use a True Musou Attack at any time.",
    "Your guard will become unbreakable.",
    "Enemies knocked back by your attack will suffer additional damage.",
    "Attack increases as more enemies are defeated.",
    "The distance an enemy is flung with a flinging attack increases.",
    "May withstand attacks even while running.",
    "The amount of time you are strengthened when a Switch Counter is successful is increased.",
    "An explosion will occur when a flinging attack is used.",
    "Each time 50 enemies are defeated the Battle God's Axe effect will occur.",
    "Each time 50 enemies are defeated the Battle God's Armor effect will occur.",
    "Each time 50 enemies are defeated the Skanda Foot effect will occur.",
    "Health decreases, but strength increases when crushing enemies.",
    "Attack increases the more allies are nearby."
]

DW8XL_ELEMENT_DESC = {i: dw8xl_edesc for i, dw8xl_edesc in enumerate(dw8xl_element_descriptions)}

# for Animal Editor
dw8xl_animals = [
    "Walnut",
    "Mahogany",
    "Birch",
    "Chestnut",
    "Maple",
    "Shadow Runner",
    "Hex Mark",
    "Red Hare",
    "Elephant",
    "Tiger",
    "Wolf",
    "Panda",
    "Bear",
    "Falcon",
    "Golden Panda",
    "Harrier",
    "War Elephant"
]
DW8XL_ANIMAL_NAMES = {i: animal for i, animal in enumerate(dw8xl_animals)}

# for animal editor
dw8xl_animal_descriptions = [
    "A brown-colored horse with a coat like that of a deer.",
    "A fawn-colored horse with traces of black.",
    "A white-colored horse with streaks of black hair.",
    "A reddish-black horse with a reddish-brown mane.",
    "A horse with a gray and white coat.",
    "Cao Cao's favorite horse. It is capable of racing across the battlefield.",
    "A horse with a white marking on its head. It is said that those who ride it meet with bad luck.",
    "An extraordinary horse said to be capable of running 1,000 li in a single day.",
    "An animal from Nanzhong, it uses its gigantic body to trample enemies on the battlefield.",
    "It uses its fearsome eyes to intimidate enemies and then attacks with its powerful claws.",
    "It attacks the enemy with its sharp claws and fangs.",
    "An exotic beast that lives in bamboo groves. With its black and white fur, it soothes those around it.",
    "It is capable of delivering a powerful blow with its front legs. It also possesses tremendous speed and strength.",
    "A bird with a razor-sharp beak. It goes straight for its prey.",
    "An exotic beast received from the Emperor. It stands out noticeably on the battlefield.",
    "An exotic beast received from the Emperor. It is very conspicuous when on the battlefield.",
    "A symbol of those that have fought successive battles and realized their ambition. Although slow, its attack strength is incredible."
]

DW8XL_ANIMAL_DESC = {i: adesc for i, adesc in enumerate(dw8xl_animal_descriptions)}

# This list of names is used by officer editor, NPC Editor, Bodyguard Editor
section_1_names = [
    "Xiahou Dun", "Dian Wei", "Sima Yi", "Zhang Liao", "Cao Cao", "Zhou Yu", "Lu Xun", 
    "Sun Shangxiang", "Gan Ning", "Sun Jian", "Zhao Yun", "Guan Yu", "Zhang Fei", 
    "Zhuge Liang", "Liu Bei", "Diaochan", "Lu Bu", "Xu Zhu", "Xiahou Yuan", "Xu Huang", 
    "Zhang He", "Cao Ren", "Cao Pi", "Taishi Ci", "Lu Meng", "Huang Gai", "Zhou Tai", 
    "Ling Tong", "Sun Ce", "Sun Quan", "Ma Chao", "Huang Zhong", "Wei Yan", "Guan Ping", 
    "Pang Tong", "Dong Zhuo", "Yuan Shao", "Zhang Jiao", "Zhenji", "Xiaoqiao", "Yueying", 
    "Meng Huo", "Cai Wenji", "Daqiao", "Jiang Wei", "Jia Xu", "Sima Shi", "Sima Zhao", 
    "Deng Ai", "Wang Yuanji", "Zhong Hui", "Zhuge Dan", "Xiahou Ba", "Guo Huai", 
    "Ding Feng", "Liu Shan", "Xingcai", "Lianshi", "Ma Dai", "Zhurong", "Guan Suo", 
    "Bao Sanniang", "Pang De", "Wang Yi", "Guo Jia", "Xu Shu", "Zuo Ci", "Yue Jin", 
    "Li Dian", "Lu Su", "Han Dang", "Guan Xing", "Zhang Bao", "Guan Yinping", "Jia Chong", 
    "Wen Yang", "Zhang Chunhua", "Yu Jin", "Zhu Ran", "Fa Zheng", "Chen Gong", "Lu Lingqi", 
    "Officer 83", "Officer 84", "Officer 85", "Officer 86", "Officer 87", "Officer 88", 
    "Officer 89", "Officer 90", "Officer 91", "Officer 92", "Officer 93", "Officer 94", 
    "Officer 95", "Officer 96", "Officer 97", "Officer 98", "Officer 99", "Officer 100", 
    "Ahui Nan", "Wei Kang", "Yi Ji", "Yin Shu", "Yin Shang", "Yin Damu", "Yin Feng", 
    "Yin Li", "Wu Yan", "Gan Ji", "Yu Jin", "Yu Quan", "Yu Mi", "Wei Yan", "Wei Kai", 
    "Wei Ji", "Yuan Yin", "Yan Yu", "Yuan Huan", "Yuan Xi", "Yan Xing", "Yan Rou", 
    "Yuan Shu", "Yuan Shang", "Yan Xiang", "Yuan Tan", "Yan Pu", "Yuan Yao", "Wang Wei", 
    "Wang Yu", "Wang Yun", "Wang Kai", "Wang Guan", "Wang Guan", "Wang Han", "Wang Ji", 
    "Wang Qi", "Wang Ye", "Wang Jinhu", "Wang Jing", "Wang Jian", "Wang Guang", 
    "Wang Hun", "Wang Can", "Wang Zan", "Wang Si", "Wang Zifa", "Wang Xiu", "Wang Su", 
    "Wang Xiang", "Wang Zhi", "Wang Chen", "Wang Zhen", "Ou Xing", "Wang Zuo", 
    "Wang Shuang", "Wang Zhong", "Wang Chang", "Wang Tao", "Wang Dun", "Wang Feixiao", 
    "Wang Ping", "Wang Fu", "Wang Fang", "Wang Mo", "Wang Mingshan", "Wang Ling", 
    "Wang Lin", "Wang Lang", "Yufuluo", "Wen Hui", "He Yan", "Kuai Yue", "Kuai Liang", 
    "Hua Yong", "Ehe", "Jia Kui", "He Yi", "Hua Xin", "E Huan", "Guo Xin", "Guo Si", 
    "Yue Jiu", "Huo Jun", "Hao Zhao", "Guo Shi", "Yue Chen", "Guo Dian", "Guo Tu", 
    "Hao Meng", "Huo Yi", "Ke Wu", "Xiahou Wei", "Xiahou En", "Xiahou He", "Xiahou Hui", 
    "Xiahou Xian", "Xiahou Xuan", "Xiahou Shang", "Xiahou Cun", "Xiahou De", "Xiahou Mao", 
    "Jia Si", "E Zhesai", "He Jin", "He Qi", "Ge Yong", "He Zhen", "Jia Fan", "He Ping", 
    "He Mao", "He Man", "Hua Xiong", "Guan Yi", "Han Yin", "Han Ying", "Huan Jia", 
    "Huan Jie", "Guan Hai", "Han Qi", "Han Qi", "Guanqiu Jian", "Guanqiu Xiu", 
    "Guanqiu Zhong", "Guanqiu Dian", "Han Qiong", "Han Xuan", "Han Hao", "Guan Gu", 
    "Han Sui", "Han Song", "Guan Jing", "Han Xian", "Han Zong", "Han Zhong", "Han De", 
    "Huan Fan", "Han Fu", "Han Meng", "Jian Yong", "Han Yao", "Yan Liang", "Qu Yi", 
    "Wei Xu", "Wei Miao", "Wei Ping", "Niu Jin", "Qiu Jian", "Niu Fu", "Qiu Ben", 
    "Gong Zhi", "Qiao Rui", "Gong Du", "Xu Yi", "Xu Gong", "Xu Si", "Xu Shao", 
    "Xu Jing", "Xu You", "Ji Ling", "Jinhuan Sanjie", "Yu Fan", "Xi Ni", "Xing Daorong", 
    "Xi Zheng", "Que Xuan", "Yan Yan", "Qian Hong", "Yan Gang", "Yan Jun", "Yan Zheng", 
    "Yan Baihu", "Yan Yu", "Wu Yi", "Ju An", "Huang She", "Hou Yin", "Gao Gan", 
    "Huang Quan", "Huang Hao", "Hao Zhou", "Kong Xiu", "Gao Rou", "Gao Shun", 
    "Huang Shao", "Gao Sheng", "Gao Xiang", "Huang Chong", "Hou Cheng", "Hou Xuan", 
    "Huang Zu", "Gao Zuo", "Gongsun Yue", "Gongsun Yuan", "Gongsun Heng", "Gongsun Zan", 
    "Gongsun Xiu", "Gongsun Xu", "Gongsun Fan", "Gao Ding", "Gao Pei", "Ju Fu", 
    "Huangfu Song", "Kong Rong", "Gao Lan", "Hu Yuan", "Wu Huan", "Wu Jing", "Wu Gang", 
    "Hu Cai", "Hu Zhi", "Huche'er", "Hu Xiu", "Hu Zun", "Hu Zhen", "Hu Ji", "Hu Zhong", 
    "King Wutugu", "Wu Dun", "Hu Ban", "Wu Ban", "Hu Fen", "Hu Feng", "Gu Yong", 
    "Wu Lan", "Hu Lie", "Cui Yan", "Cai Mao", "Cai Yang", "Cai Yong", "Cui Liang", 
    "Ze Rong", "Zuo Ling", "Shi Kuan", "Shi Huan", "Shi Zuan", "Shi Zhao", "Sima Kui", 
    "Sima Ju", "Sima Xun", "Sima Jin", "Sima Tong", "Sima Min", "Sima Fu", "Sima Wang", 
    "Sima You", "Sima Lang", "Shamoke", "Zhu Yi", "Zhou Xin", "Zhou Qun", "Zhou Cang", 
    "Zhou Tai", "Zhou Chao", "Xi Zhen", "Zhou Fang", "Zhu En", "Zhu Gai", "Zhu Huan", 
    "Su Shu", "Zhu Guang", "Zhu Zan", "Zhu Jun", "Zhu Ji", "Zhu Ran", "Zhu Zhi", 
    "Zhu Fang", "Zhu Bao", "Zhu Ling", "Xun Yu", "Chunyu Qiong", "Xun Kai", "Xun Xu", 
    "Xun Chen", "Xun You", "Jiao Yi", "Jiang Wan", "Shaoge", "Jiang Gan", 
    "Shangguan Zixiu", "Zhong Yi", "Jiang Qin", "Qiao Zhou", "Zhong Jun", "Zhong Jun", 
    "Jiang Shu", "Jiao Chu", "Jiang Ji", "Xiang Chong", "Chang Diao", "Shao Ti", 
    "Zhong Chan", "Jiao Bo", "Jiang Ban", "Jiang Bin", "Zhong Yu", "Zhong Yao", 
    "Zhong Yong", "Xiang Lang", "Xu Rong", "Xu He", "Zhuge Ke", "Zhuge Jin", 
    "Zhuge Jun", "Zhuge Jing", "Zhuge Gui", "Zhuge Xuan", "Zhuge Zhi", "Zhuge Xu", 
    "Zhuge Shang", "Zhuge Zhan", "Zhuge Rong", "Xu Qiu", "Xu Zhi", "Xu Shang", 
    "Xu Shao", "Xu Sheng", "Xu Xuan", "Qin Qi", "Shen Yi", "Qin Xie", "Ren Jun", 
    "Xin Chang", "Shen Dan", "Ren Du", "Shen Pei", "Xin Pi", "Xin Ping", "Cen Bi", 
    "Qin Lang", "Zou Dan", "Cheng He", "Cheng Yi", "Cheng Gongying", "Cheng Cui", 
    "Cheng Ji", "Cheng Lian", "Shi Bao", "Xue Qiao", "Xue Zong", "Xue Ze", "Xue Ti", 
    "Xue Li", "Quan Yi", "Quan Yi", "Quan Xi", "Dan Jing", "Dan Gu", "Quan Ji", 
    "Quan Jing", "Quan Zong", "Quan Duan", "Quan Pian", "Cao Anmin", "Cao Yu", 
    "Cao Rui", "Song Guo", "Cao Xi", "Cao Xiu", "Cao Xun", "Song Xian", "Song Qian", 
    "Cao Hong", "Cao Ang", "Zong Ziqing", "Cao Chun", "Cao Zun", "Cao Zhang", "Cao Zhi", 
    "Cao Zhen", "Cao Xing", "Cao Shuang", "Cao Tai", "Cao Zhen", "Zang Ba", "Cao Bao", 
    "Zong Bao", "Cao Mao", "Zong Yu", "Ju Shou", "Su Fei", "Supuyan", "Zu Mao", 
    "Sun Huan", "Sun Guan", "Sun Yi", "Sun Xiu", "Sun Kuang", "Sun Qian", "Sun Xian", 
    "Sun Qian", "Sun Jun", "Sun Shao", "Sun Jing", "Sun Zong", "Sun Tai", "Sun Zhong", 
    "Sun Chen", "Sun Deng", "Sun Ben", "Sun Man", "Sun Li", "Sun Lang", "Taishi Xiang", 
    "Dailai Dongzhu", "Dai Ling", "Zhuo Ying", "King Duosi", "Zhi Wudai", "Zhang Yun", 
    "Zhang Ying", "Zhang Wei", "Zhang Ying", "Zhang Yan", "Zhang Heng", "Zhang Wen", 
    "Zhang Ji", "Zhang Qiu", "Zhang Yi", "Zhang Xun", "Zhao Yue", "Zhao Yan", 
    "Zhang Hu", "Zhang Hu", "Zhao Hong", "Zhao Guang", "Zhang Xiu", "Zhang Ji", 
    "Zhang Zun", "Zhang Cheng", "Zhang Zhao", "Zhang Shao", "Zhang Chang", "Zhang Shi", 
    "Zhang Zhen", "Zhang Ren", "Zhang Ji", "Zhang Sheng", "Zhang Quan", "Zhang Xian", 
    "Zhang Da", "Zhang Chao", "Zhao Zhi", "Zhao Tong", "Zhang Te", "Zhang Nan", 
    "Zhang Miao", "Zhao Fan", "Zhang Pu", "Zhang Fu", "Zhang Bao", "Zhang Mancheng", 
    "Zhang Ming", "Zhang Yue", "Zhang Yi", "Zhang Liang", "Zhao Lei", "Zhang Lu", 
    "Chen Heng", "Chen Ying", "Chen Ji", "Chen Gong", "Chen Jiao", "Chen Qun", 
    "Chen Gui", "Chen Qian", "Chen Zhi", "Chen Shou", "Chen Jiu", "Chen Jun", 
    "Chen Shi", "Chen Zhen", "Chen Sheng", "Chen Zao", "Chen Tai", "Chen Deng", 
    "Chen Dao", "Chen Wu", "Chen Lan", "Chen Lin", "Cheng Yu", "Zheng Yien", 
    "Cheng Yuanzhi", "Cheng Yin", "Ding Yuan", "Zheng Xuan", "Zheng Du", "Ding Mi", 
    "Cheng Pu", "Cheng Wu", "Zheng Wen", "Ding Feng", "Zhai Yuan", "Tian Kai", 
    "Tian Zhang", "Tian Xu", "Tian Feng", "Dian Man", "Tian Yu", "Tu An", "Teng Yin", 
    "Dong Yun", "Dong Yue", "Dong He", "Dong Xi", "Dang Jun", "Dong Jue", "Deng Xian", 
    "Tao Qian", "Dong Heng", "Dong Huang", "Deng Zhi", "Tang Zi", "Dong Xi", 
    "Dong Zhao", "Dong Cheng", "Deng Ji", "Deng Zhong", "Dong Chao", "Dong Tuna", 
    "Tadun", "Dong Min", "Deng Mao", "Deng Yang", "Dongli Gun", "Deng Long", 
    "Deng Liang", "Du Rui", "Du Qi", "Du Xi", "Ning Sui", "Pei Yuanshao", "Pei Xiu", 
    "Ma Han", "Ma Wan", "Ma Yuanyi", "Bo Cai", "Ma Richan", "Ma Zun", "Ma Su", 
    "Ma Zhong", "Ma Zhong", "Ma Teng", "Ma Miao", "Ma Long", "Ma Liang", "Pan Ju", 
    "Fan Jiang", "Fan Yi", "Fan Jian", "Pan Jun", "Pan Zhang", "Pan Sui", "Fan Chou", 
    "Fan Neng", "Fan Fang", "Fan You", "Pan Lin", "Fei Yi", "Bei Yan", "Fei Guan", 
    "Fei Shi", "Mi Zhu", "Fei Zhan", "Mi Fang", "Fei Yao", "Wu Anguo", "Feng Kai", 
    "Feng Xi", "Fu Wan", "Fu Shiren", "Fu Qian", "Fu Xun", "Fu Tong", "Fu Fang", 
    "Wen Qin", "Wen Hu", "Wen Chou", "Wen Ze", "Wen Pin", "Bing Yuan", "Bian Xi", 
    "Bian Zhang", "Pang Hui", "Mang Yachang", "Feng Ji", "Pang Yi", "Bao Xin", 
    "Fa Zheng", "Bao Su", "Bao Zhong", "Peng Yang", "Bao Long", "King Mulu", 
    "Man Chong", "King Midang", "Meng Da", "Meng You", "You Tu", "Yu She", "Yang Wei", 
    "Yang Huai", "Yong Kai", "Yang Yi", "Yang Xi", "Yang Xin", "Yang Hong", 
    "Yang Kang", "Yang Hong", "Yang Ang", "Yang Xiu", "Yang Qiu", "Yang Song", 
    "Yang Ren", "Yang Zuo", "Yang Zong", "Yang Ding", "Yang Bo", "Yang Biao", 
    "Yang Fu", "Yang Feng", "Yang Feng", "Yang Ling", "Lei Xu", "Lei Tong", "Lei Bo", 
    "Lai Min", "Luo Xian", "Li Hui", "Li Jue", "Li Yue", "Li Kan", "Li Jian", 
    "Li Qiu", "Li Xin", "Lu Kai", "Lu Kang", "Lu Ji", "Li Qian", "Li Yan", "Li Ru", 
    "Li Su", "Li Sheng", "Li Tiao", "Li Xu", "Li Zhuan", "Li Tong", "Li Fu", "Li Fu", 
    "Li Feng", "Li Feng", "Li Peng", "Li Meng", "Liu A", "Liu Yin", "Liu Yong", 
    "Liu Yan", "Liu Yan", "Liu Yan", "Liu Yuan", "Liu Gui", "Liu Xie", "Liu Qi", 
    "Liu Qin", "Liu Xun", "Liu Xian", "Liu Zan", "Liu Zuan", "Liu Jun", "Liu Xun", 
    "Liu Zhang", "Liu Shao", "Liu Chen", "Liu Dai", "Liu Da", "Liu Du", "Liu Ning", 
    "Liu Ba", "Liu Biao", "Liu Bao", "Liu Min", "Liu Ping", "Liu Pi", "Liu Fu", 
    "Liu Feng", "Liu Yao", "Liu Ye", "Liu Lue", "Lu Weihuang", "Liao Hua", 
    "Liang Qian", "Liang Gang", "Liang Xing", "Liang Xu", "Ling Cao", "Lu Yi", 
    "Lu Ju", "Lu Jian", "Lu Qian", "Lu Kuang", "Lu Gong", "Lu Xiang", "Lu Chang", 
    "Lu Dai", "Lu Fan", "Lu You", "Lun Zhi", "Li Fei", "Leng Bao", "Lou Xuan", 
    "Lu Zhi", "Lu Zhao", "Lu Zhi", "Zhang Rang", "Duan Gui", "Zhao Zhong", "Cao Jie", 
    "Hou Lan", "Jian Shuo", "Cheng Kuang", "Xia Yun", "Guo Sheng", "Feng Xu", 
    "Yu Digen", "Zhang Baiqi", "Zhang Leigong", "Yu Du", "Zuo Zizhangba", "Li Damu", 
    "Guo Daxian", "Sui Gu", "Bai Rao", "Sun Sheng", "Zhuangzi", "Liu Cong", "Wu Zi", 
    "Li Feng", "Xue Lan", "Placeholder", "Placeholder", "Placeholder", "Placeholder", 
    "Placeholder", "Placeholder", "Placeholder", "Placeholder", "Placeholder", 
    "Placeholder", "Placeholder", "Placeholder", "Placeholder"
]

# Generate the main dictionary with accurate BIN IDs (0-837)
UNIT_NAMES = {i: name for i, name in enumerate(section_1_names)}

BODYGUARD_NAMES = {i: guard for i, guard in enumerate(section_1_names)}

# Append Section 2 for unit names, Non-sequential unit IDs

UNIT_NAMES.update({
    900: "Unit Commander", 901: "Major", 902: "Corporal", 903: "Private", 
    904: "Elite Guard", 905: "Base Captain", 906: "Cavalry", 907: "Archer", 
    908: "Engineer", 909: "Thrower", 910: "Ensign", 911: "Brigadeer General", 
    912: "Peasant", 913: "Defense Captain", 914: "Assault Captain", 915: "Tiger", 
    916: "Fire Archer", 917: "Militiaman", 918: "Supply Captain", 919: "Messenger", 
    920: "Sorcery Troop", 921: "Battle Troop", 922: "Guard", 923: "Carriage", 
    924: "Assassin", 925: "Phantom Soldier", 926: "Mystic", 927: "Catapult 1", 
    928: "Ram", 929: "Arbalest", 930: "Ballista", 931: "Juggernaut", 
    932: "Pyrocannon", 933: "Siege Tower", 934: "Catapult 2", 935: "Cart", 
    936: "Wood Ox", 937: "Handmaiden", 938: "Minister", 940: "Wolf", 
    941: "Panda", 942: "Blacksmith", 943: "Academy", 944: "Merchant", 
    945: "Barracks", 946: "Teahouse", 947: "Training Ground", 948: "Farmer", 
    949: "Stables", 950: "Messenger", 951: "Gatekeeper", 952: "Mobile Unit Captain", 
    953: "Engineer", 954: "Flaming Catapult 1", 955: "Flaming Catapult 2", 
    956: "Siege Ramp", 957: "Bridgelayer", 958: "Flowing Horse", 959: "Bear", 
    960: "Elephant", 961: "Falcon", 962: "Horse", 963: "Emperor", 
    964: "Spy", 965: "Torch Troop", 967: "Bandit Leader", 968: "Bandit Lieutenant", 
    969: "Fire Attack Captain", 970: "Emperor Imposter"
})

# For support skill editor
dw8xl_off_sup_skill_names = [
    "Sprint - Shadow",
    "Sprint - Encouragement",
    "Sprint - Charge",
    "Sprint - Endurance",
    "Sprint - Growth",
    "Sprint - Recovery",
    "Sprint - Swimming",
    "Sprint - Penetrate",
    "Assistance - Recovery",
    "Assistance - Assault",
    "Assistance - Protect",
    "Assistance - Energy",
    "Assistance - Healing",
    "Assistance - Rally",
    "Assistance - Discovery",
    "Assistance - Growth",
    "Assistance - Affluence",
    "Rouse - Recovery",
    "Rouse - Assault",
    "Rouse - Protect",
    "Supplement - Dash",
    "Success Effect - Dash",
    "Success Effect - Assault",
    "Success Effect - Protect",
    "Success Effect - Energy",
    "Conclusion - Recovery",
    "Conclusion - Assault",
    "Conclusion - Protect",
    "Conclusion - Energy",
    "Conclusion - Rage",
    "Signal - Energy",
    "Signal - Rage",
    "Bodyguard - Rigidity",
    "Bodyguard - Restore",
    "Bodyguard - Feats"
]

DW8XL_SUPPORT_SKILL_NAMES = {i: ssname for i, ssname in enumerate(dw8xl_off_sup_skill_names)}

# for support skill editor
dw8xl_sup_skill_desc = [
    "Eliminates the damage taken from arrows while you are running.",
    "Slowly fills your Musou Gauge while riding.",
    "Increases the damage inflicted on enemies when charging into them.",
    "Prevents you from being knocked from your mount when attacked.",
    "Gives you an EXP bonus when defeating enemies.",
    "Restores the Health Gauge of a rider that is near death.",
    "Increases the speed at which you can move through water.",
    "Crashing into an enemy will not slow down your sprinting speed.",
    "Restores your Health when your character is near death.",
    "Increases your Attack when your character is near death.",
    "Increases your Defense when your character is near death.",
    "Restores 1 unit of your Musou Gauge when your character is near death.",
    "Slowly restores your Health Gauge when your character is near death.",
    "Slowly restores your Musou Gauge when your character is near death.",
    "Enemies may occasionally drop items when defeated.",
    "Enemies may occasionally drop growth items when defeated.",
    "Enemies may occasionally drop Gold when defeated.",
    "Restores the Health of bodyguards that are near death.",
    "Increases the Attack of bodyguards that are near death.",
    "Increases the Defense of bodyguards that are near death.",
    "Increases your Speed when skills are used.",
    "Increases your Speed when a skill is successful.",
    "Increases your Attack when a skill is successful.",
    "Increases your Defense when a skill is successful.",
    "Restores one unit of your Musou Gauge when a skill is successful.",
    "Restores your Health when your battle skills are used up.",
    "Increases your Attack when your battle skills are used up.",
    "Increases your Defense when your battle skills are used up.",
    "Restores your Musou Gauge when your battle skills are used up.",
    "Restores your Rage Gauge when your battle skills are used up.",
    "Fills your Musou Gauge at the start of a battle.",
    "Fills your Rage Gauge at the start of a battle.",
    "Overall abilities of bodyguards are strengthened.",
    "Bodyguards that have fled can be returned to the battle once.",
    "Feats earned by bodyguards will come with a bonus."
]

DW8XL_SUPPORT_SKILL_DESC = {i: sdesc for i, sdesc in enumerate(dw8xl_sup_skill_desc)}

# for officer skill editor
dw8xl_officer_skill_names = [
    "Accuracy", "Quick Learner", "Fortune Hunter", "Victory Cry", "Health Springs", 
    "Musou Springs", "Rage Springs", "Burning Spirit", "Secret Arts", "Nullification", 
    "Equestrian", "Havoc", "Health Boost", "Attack Boost", "Defense Boost", 
    "Mighty Roar", "Steely Heart", "Determination", "Podao", "Axe", 
    "Horsehair Whip", "Twin Axes", "General's Sword", "Staff", "Swallow Swords", 
    "Wheels", "Flail", "Nine Ring Blade", "Dragon Spear", "Crescent Blade", 
    "Double Pike", "War Fan", "Twin Swords", "Chain Whip", "Halberd", 
    "Club", "Bow & Rod", "Great Axe", "Claws", "Spiked Shield", 
    "Dual Blade", "Twin Rods", "Pike", "Arm Blade", "Curved Sword", 
    "Tri-Staff", "Tonfa", "Sword", "Spear", "Bow", 
    "Double Voulge", "Great Sword", "Shadow Fan", "Bomb", "Extension Blade", 
    "Shaman Rod", "Flute", "Iron Fan", "Dagger-axe", "Gloves", 
    "Harp", "Pugil Stick", "Double Trident", "Chain & Sickle", "Lightning Sword", 
    "Striking Sword", "Lance", "Throwing Knives", "Flying Swords", "Short Rods", 
    "Siege Spear", "Arm Cannon", "Circle Blade", "Rapier", "Sword & Shield", 
    "Crossbow", "Brush", "Boomerang", "Nunchaku", "Spinner", 
    "Mace", "Trishula", "Orb & Scepter", "Sword & Hook", "Talisman Cards", 
    "Dual Hookblades", "Wheeled Halberd", "Rake", "Short Pike", "Wingblades", 
    "Flail Sword", "Dual-head Mace", "Throwing Axes", "Javelin", "Wired Gloves", 
    "Dasher", "Diver", "Shadow Sprinter", "Wind Master", "War Trident", 
    "Flame Bow", "Woven Cloth", "Art of War Scroll", "Crossed Pike"
]

DW8XL_OFF_SKILL_NAMES = {i: sname for i, sname in enumerate(dw8xl_officer_skill_names)}

# for officer skill editor
dw8xl_officer_skill_desc = [
    "Increases your chance of a critical hit.",
    "Adds a bonus to the EXP you earn.",
    "Increases Luck.",
    "Increases the chances that items will appear in battle.",
    "Adds a bonus to your Health Gauge recovery.",
    "Adds a bonus to refilling your Musou Gauge.",
    "Adds a bonus to refilling your Rage Gauge.",
    "Increases the duration of power-up items.",
    "Resistance against ranged attacks increases.",
    "Increases resistance against elemental attacks.",
    "Improves your equestrian skills.",
    "Increases your attack range.",
    "Increases the maximum size of your Health Gauge.",
    "Increases your Attack.",
    "Increases your Defense.",
    "Increases the damage you inflict against enemy officers.",
    "Decreases the damage you receive from enemy officers.",
    "Restores some of your Health when you are knocked down.",
    "Able to use Shadow Sprint when a Podao is equipped.",
    "Able to use Whirlwind when an Axe is equipped.",
    "Able to use Dive when a Horsehair Whip is equipped.",
    "Able to use Whirlwind when Twin Axes are equipped.",
    "Able to use Shadow Sprint when a General's Sword is equipped.",
    "Able to use Dash when a Staff is equipped.",
    "Able to use Dash when Swallow Swords are equipped.",
    "Able to use Dash when a Wheel is equipped.",
    "Able to use Shadow Sprint when a Flail is equipped.",
    "Able to use Shadow Sprint when a Nine Rings Blade is equipped.",
    "Able to use Dive when a Dragon Spear is equipped.",
    "Able to use Dive when a Crescent Blade is equipped.",
    "Able to use Shadow Sprint when a Double Pike is equipped.",
    "Able to use Dash when a War Fan is equipped.",
    "Able to use Dash when Twin Swords are equipped.",
    "Able to use Dash when a Chain Whip is equipped.",
    "Able to use Whirlwind when a Halberd is equipped.",
    "Able to use Whirlwind when a Club is equipped.",
    "Able to use Whirlwind when a Bow & Rod are equipped.",
    "Able to use Whirlwind when a Great Axe is equipped.",
    "Able to use Dash when Claws are equipped.",
    "Able to use Whirlwind when a Spiked Shield is equipped.",
    "Able to use Dive when a Dual Blade is equipped.",
    "Able to use Whirlwind when Twin Rods are equipped.",
    "Able to use Whirlwind when a Pike is equipped.",
    "Able to use Whirlwind when an Arm Blade is equipped.",
    "Able to use Dash when a Curved Sword is equipped.",
    "Able to use Dash when a Three Sectional Staff is equipped.",
    "Able to use Whirlwind when a Tonfa is equipped.",
    "Able to use Dash when a Sword is equipped.",
    "Able to use Whirlwind when a Spear is equipped.",
    "Able to use Dash when a Bow is equipped.",
    "Able to use Whirlwind when a Double Voulge is equipped.",
    "Able to use Whirlwind when a Great Sword is equipped.",
    "Able to use Dash when a Shadow Fan is equipped.",
    "Able to use Whirlwind when a Bomb is equipped.",
    "Able to use Dash when an Extension Blade is equipped.",
    "Able to use Dash when a Shaman Rod is equipped.",
    "Able to use Dash when a Flute is equipped.",
    "Able to use Dash when an Iron Fan is equipped.",
    "Able to use Whirlwind when a Dagger-axe is equipped.",
    "Able to use Whirlwind when Gloves are equipped.",
    "Able to use Dash when a Harp is equipped.",
    "Able to use Dash when a Pugil Stick is equipped.",
    "Able to use Shadow Sprint when a Double-edge Trident is equipped.",
    "Able to use Dash when a Chain & Sickle are equipped.",
    "Able to use Dash when a Lightning Sword is equipped.",
    "Able to use Dive when a Striking Sword is equipped.",
    "Able to use Whirlwind when a Lance is equipped.",
    "Able to use Dash when Throwing Knives are equipped.",
    "Able to use Dash when a Flying Sword is equipped.",
    "Able to use Shadow Sprint when a Short Rod is equipped.",
    "Able to use Whirlwind when a Siege Spear is equipped.",
    "Able to use Whirlwind when an Arm Cannon is equipped.",
    "Able to use Whirlwind when a Circle Blade is equipped.",
    "Able to use Dash when a Rapier is equipped.",
    "Able to use Dash when a Sword & Shield are equipped.",
    "Able to use Whirlwind when a Crossbow is equipped.",
    "Able to use Whirlwind when a Brush is equipped.",
    "Able to use Dash when a Boomerang is equipped.",
    "Able to use Dash when a Nunchaku is equipped.",
    "Able to use Dash when a Spinner is equipped.",
    "Able to use Whirlwind when a Mace is equipped.",
    "Able to use Dash when a Trishula is equipped.",
    "Able to use Dash when an Orb & Scepter are equipped.",
    "Able to use Dash when a Sword & Hook are equipped.",
    "Able to use Dive when Talisman Cards are equipped.",
    "Able to use Dash when Dual Hookblades are equipped.",
    "Able to use Whirlwind when a Wheeled Halberd is equipped.",
    "Able to use Whirlwind when a Rake is equipped.",
    "Able to use Whirlwind when a Short Pike is equipped.",
    "Able to use Dash when Wingblades are equipped.",
    "Able to use Dive when a Flail Sword is equipped.",
    "Able to use Whirlwind when a Dual-headed Mace is equipped.",
    "Able to use Dash when Throwing Axes are equipped.",
    "Able to use Shadow Sprint when a Javelin is equipped.",
    "Able to use Dash when Wired Gloves are equipped.",
    "Able to use Dash with all of the Dash Weapons.",
    "Able to use Dive with all of the Dive Weapons.",
    "Able to use Shadow Sprint with all of the Shadow Sprint Weapons.",
    "Able to use Whirlwind with all of the Whirlwind Weapons.",
    "Able to use Whirlwind when a War Trident is equipped.",
    "Able to use Dash when a Flame Bow is equipped.",
    "Able to use Dive when a Woven Cloth is equipped.",
    "Able to use Dash when an Art of War Scroll is equipped.",
    "Able to use Shadow Sprint when a Crossed Pike is equipped."
]

DW8XL_OFF_SKILL_DESC = {i: desc for i, desc in enumerate(dw8xl_officer_skill_desc)}
